services:
  postgres:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "${DB_PORT}:5432"

  # app:
  #   build: .
  #   environment:
  #     - NODE_ENV=production
  #     - DB_USER=${DB_USER}
  #     - DB_PASSWORD=${DB_PASSWORD}
  #     - DB_NAME=${DB_NAME}
  #     - DB_HOST=postgres
  #     - DB_PORT=${DB_PORT}
  #     - PORT=${PORT}
  #     - SECRET_KEY=${SECRET_KEY}
  #   ports:
  #     - "4000:4000"
  #   depends_on:
  #     - postgres
  #   entrypoint: sh -c "npm run run-migrations && npm start"

volumes:
  postgres_data:
